"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/cartContext";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Real Food Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} h-full bg-slate-100`}
      >
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
